#!/bin/bash
# This was automatically generated by a script.

# /d/Projects/reference/microsoft/aspnet/aspnet-docker
git clone https://github.com/aspnet/aspnet-docker.git aspnet/aspnet-docker/
# /d/Projects/reference/microsoft/aspnet/AspNetCore
git clone https://github.com/aspnet/AspNetCore.git aspnet/AspNetCore/
# /d/Projects/reference/microsoft/aspnet/BuildTools
git clone https://github.com/aspnet/BuildTools.git aspnet/BuildTools/
# /d/Projects/reference/microsoft/aspnet/CORS
git clone https://github.com/aspnet/CORS.git aspnet/CORS/
# /d/Projects/reference/microsoft/aspnet/EntityFrameworkCore
git clone https://github.com/aspnet/EntityFrameworkCore.git aspnet/EntityFrameworkCore/
# /d/Projects/reference/microsoft/aspnet/Extensions
git clone https://github.com/aspnet/Extensions.git aspnet/Extensions/
# /d/Projects/reference/microsoft/aspnet/Hosting
git clone https://github.com/aspnet/Hosting.git aspnet/Hosting/
# /d/Projects/reference/microsoft/aspnet/HttpAbstractions
git clone https://github.com/aspnet/HttpAbstractions.git aspnet/HttpAbstractions/
# /d/Projects/reference/microsoft/aspnet/IISIntegration
git clone https://github.com/aspnet/IISIntegration.git aspnet/IISIntegration/
# /d/Projects/reference/microsoft/aspnet/KestrelHttpServer
git clone https://github.com/aspnet/KestrelHttpServer.git aspnet/KestrelHttpServer/
# /d/Projects/reference/microsoft/aspnet/MetaPackages
git clone https://github.com/aspnet/MetaPackages.git aspnet/MetaPackages/
# /d/Projects/reference/microsoft/aspnet/Mvc
git clone https://github.com/aspnet/Mvc.git aspnet/Mvc/
# /d/Projects/reference/microsoft/aspnet/Razor
git clone https://github.com/aspnet/Razor.git aspnet/Razor/
# /d/Projects/reference/microsoft/aspnet/Routing
git clone https://github.com/aspnet/Routing.git aspnet/Routing/
# /d/Projects/reference/microsoft/aspnet/websdk
git clone https://github.com/aspnet/websdk.git aspnet/websdk/
# /d/Projects/reference/microsoft/aspnet-archived/JsonPatch
git clone https://github.com/aspnet/JsonPatch.git aspnet-archived/JsonPatch/
# /d/Projects/reference/microsoft/dotnet/arcade
git clone https://github.com/dotnet/arcade.git dotnet/arcade/
# /d/Projects/reference/microsoft/dotnet/arcade-minimalci-sample
git clone https://github.com/dotnet/arcade-minimalci-sample dotnet/arcade-minimalci-sample/
# /d/Projects/reference/microsoft/dotnet/arcade-services
git clone https://github.com/dotnet/arcade-services.git dotnet/arcade-services/
# /d/Projects/reference/microsoft/dotnet/buildtools
git clone https://github.com/dotnet/buildtools.git dotnet/buildtools/
# /d/Projects/reference/microsoft/dotnet/cli
git clone https://github.com/dotnet/cli.git dotnet/cli/
# /d/Projects/reference/microsoft/dotnet/CliCommandLineParser
git clone https://github.com/dotnet/CliCommandLineParser.git dotnet/CliCommandLineParser/
# /d/Projects/reference/microsoft/dotnet/core
git clone https://github.com/dotnet/core.git dotnet/core/
# /d/Projects/reference/microsoft/dotnet/core-sdk
git clone https://github.com/dotnet/core-sdk.git dotnet/core-sdk/
# /d/Projects/reference/microsoft/dotnet/core-setup
git clone https://github.com/dotnet/core-setup.git dotnet/core-setup/
# /d/Projects/reference/microsoft/dotnet/coreclr
git clone https://github.com/dotnet/coreclr.git dotnet/coreclr/
# /d/Projects/reference/microsoft/dotnet/corefx
git clone https://github.com/dotnet/corefx.git dotnet/corefx/
# /d/Projects/reference/microsoft/dotnet/corefxlab
git clone https://github.com/dotnet/corefxlab.git dotnet/corefxlab/
# /d/Projects/reference/microsoft/dotnet/docfx
git clone https://github.com/dotnet/docfx.git dotnet/docfx/
# /d/Projects/reference/microsoft/dotnet/docker-tools
git clone https://github.com/dotnet/docker-tools.git dotnet/docker-tools/
# /d/Projects/reference/microsoft/dotnet/dotnet-ci
git clone https://github.com/dotnet/dotnet-ci.git dotnet/dotnet-ci/
# /d/Projects/reference/microsoft/dotnet/dotnet-docker
git clone https://github.com/dotnet/dotnet-docker.git dotnet/dotnet-docker/
# /d/Projects/reference/microsoft/dotnet/metadata-tools
git clone https://github.com/dotnet/metadata-tools.git dotnet/metadata-tools/
# /d/Projects/reference/microsoft/dotnet/orleans
git clone https://github.com/dotnet/orleans.git dotnet/orleans/
# /d/Projects/reference/microsoft/dotnet/orleans-templates
git clone https://github.com/dotnet/orleans-templates.git dotnet/orleans-templates/
# /d/Projects/reference/microsoft/dotnet/project-system
git clone https://github.com/dotnet/project-system.git dotnet/project-system/
# /d/Projects/reference/microsoft/dotnet/project-system-tools
git clone https://github.com/dotnet/project-system-tools.git dotnet/project-system-tools/
# /d/Projects/reference/microsoft/dotnet/ProjFileTools
git clone https://github.com/dotnet/ProjFileTools.git dotnet/ProjFileTools/
# /d/Projects/reference/microsoft/dotnet/roslyn-analyzers
git clone https://github.com/dotnet/roslyn-analyzers.git dotnet/roslyn-analyzers/
# /d/Projects/reference/microsoft/dotnet/roslyn-sdk
git clone https://github.com/dotnet/roslyn-sdk.git dotnet/roslyn-sdk/
# /d/Projects/reference/microsoft/dotnet/roslyn-tools
git clone https://github.com/dotnet/roslyn-tools.git dotnet/roslyn-tools/
# /d/Projects/reference/microsoft/dotnet/sdk
git clone https://github.com/dotnet/sdk.git dotnet/sdk/
# /d/Projects/reference/microsoft/dotnet/standard
git clone https://github.com/dotnet/standard.git dotnet/standard/
# /d/Projects/reference/microsoft/dotnet/templates
git clone https://github.com/dotnet/templates.git dotnet/templates/
# /d/Projects/reference/microsoft/dotnet/toolset
git clone https://github.com/dotnet/toolset.git dotnet/toolset/
# /d/Projects/reference/microsoft/dotnet/versions
git clone https://github.com/dotnet/versions.git dotnet/versions/
# /d/Projects/reference/microsoft/dotnet-architecture/eShopOnWeb
git clone https://github.com/dotnet-architecture/eShopOnWeb.git dotnet-architecture/eShopOnWeb/
# /d/Projects/reference/microsoft/reference-source
git clone https://github.com/Microsoft/referencesource.git reference-source/
