#!/bin/bash

# store the current dir
CUR_DIR=$(pwd)
OUTFILE=$(pwd)/checkout-all.sh

echo "#!/bin/bash" >$OUTFILE;
echo "# This was automatically generated by a script." >>$OUTFILE;
echo "" >>$OUTFILE;

# Let the person running the script know what's going on.
echo -e "\n\033[1mListing remotes for all repositories...\033[0m\n"

# Find all git repositories and update it to the master latest revision
for i in $(find . -name .git -type d | cut -c 3-); do
    echo "";
    echo -e "\033[33m"+$i+"\033[0m";

    # We have to go to the .git parent directory to call the pull command
    cd "$i";
    cd ..;

    foldername=$(basename "$(pwd)")
    remoteurl=$(git remote get-url origin)
    echo "origin: $remoteurl";
    echo "# $(pwd)" >>$OUTFILE;
    echo "git clone $remoteurl ${i//.git/}" >>$OUTFILE;

    # lets get back to the CUR_DIR
    cd $CUR_DIR
done

echo -e "\n\033[32mComplete!\033[0m\n"